version: "3.0"
services:
  app:
    build: .
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - home:/root
    environment:
      DISPLAY: $DISPLAY
    security_opt:
      - seccomp:unconfined

volumes:
  home:
